### ISSUE TITLE
Pull Requests for code updates?

### ISSUE THREAD

**Issue by bluepeter** [pilwon/ultimate-seed#102]
Hi guys: Any chance you can do PRs for new code updates? That way they'll appear as issues and us watchers can get alerts. Also, it'll help to better isolate code around specific features/etc.

**Comment by pilwon** [comment]
@bluepeter We appreciate your excellent suggestion. We actually discussed that internally already, and our conclusion was to keep it the same way for now. The biggest reason was because it would introduce us some overhead and possibly slow down the process, when we already have limited time and resources to maintain this project.

Just to give you a better idea.. if you look at many other popular decent sized open source projects, you will see they don't necessarily create an issue for every single code change they make. The updates and directions of a project are often discussed and finalized internally amongst the core group of repo collaborators, while still considering all the external inputs. Code contributions and feedback from the users are still extremely valuable for these projects.

We'd like to keep our project similar to most others for now, but we do understand there's a room for improvement on how we do things for this project. We expect these things will get better over time. One thing we recently started was tagging our releases. NPM also recently changed their `npm publish` policy to "cannot publish over existing version", so it forces us to do a better job with versioning and publishing. We will continue to welcome PRs and good suggestions/ideas like yours, so we can make this project more widely accepted. Thanks again!
