### ISSUE TITLE
Question: documentation/third-party redirect handler?

### ISSUE THREAD

**Issue by bluepeter** [pilwon/ultimate-seed#104]
Hi guys:

Mind pointing me to any documentation on the redirection syntax in, e.g., https://github.com/pilwon/ultimate-seed/blob/5e5c129e1494da23e16bd5227c0af8d20af0b63b/client/js/auth/index.js#L44-L48

I see the custom redirect service, but not sure if there's some documentation of the various rules? These rules don't appear to be part of angular-ui?

**Comment by pilwon** [comment]
@bluepeter This is from our custom `route` service. You can find it in the shared module. Check [this code](https://github.com/pilwon/ultimate-seed/blob/5e5c129e1494da23e16bd5227c0af8d20af0b63b/client/js/shared/services/route.js#L21) It is based on `ui-router`.

**Comment by bluepeter** [comment]
Thanks, yeah, I saw that... for these sorts of things might be cool to eventually add comments a la, for example, https://github.com/angular-ui/ui-router/blob/master/src/urlMatcherFactory.js

**Comment by pilwon** [comment]
@bluepeter Yeah I completely agree that we should have something like that soon.

We prefer not to mix the comment/documentation with the source code though, because this is a seed project rather than a full framework or library module. We believe if you already know how to use the seed then you would not want too many comments pre-occupied in the project. You might prefer to include your own comments. So when we do a proper job with documentation in the next major version, we will probably choose standalone documentation.

This project is still quite young and we lack resources. You are among the first few developers that are willing to spend time to learn this poorly documented project inside out. We'd love to have you contributing to this open source project with documentation (and other parts) once you figure out this puzzle.

**Comment by bluepeter** [comment]
Thanks, good points. Yep, I hope to contribute lots more once I come up to speed not only on your project but all the associated technologies! I hope to launch a little alpha Twitter analytics site using Ultimate next week or so. (I'll let you know when it's live.)

**Comment by pilwon** [comment]
@bluepeter I'm very excited to hear that. Please share it with us if possible. This project was started out of my personal needs (there was nothing out there like this one), but as you might have seen it already, there is some great value offered by this project. It can potentially help a lot more node.js developers with their projects. With your contributions we can really make this happen. (and make the world a better place! :dancers:)

**Comment by kerimdzhanov** [comment]
You're very impressed me guys! I'm following you! :+1:
