### ISSUE TITLE
Outdated dependencies (PR proposal)

### ISSUE THREAD

**Issue by kerimdzhanov** [pilwon/ultimate-seed#105]
Hi to all! I would like to go through the outdated dependencies and update them to the latest appropriate versions in `package.json`. I won't update a major numbers for now, because it may take much longer time than i expect, but there are already many dependencies that lacks some latest bug fixes and probably optimizations.

To make my PR valuable and not just wasting a time i would like to hear any suggestions from you regarding to this PR. Is there any known pitfalls or reasons for not doing this?

And if it's ok, can i use `~>` when defining a version numbers? Currently all the dependencies are defined with exact version numbers, for example:

```
"barbeque": "0.2.1",
```

but @pilwon already released "0.2.3" :+1:. So if we believe that developers adhere semantic versioning rules, and we have a `package.json` entry like:

```
"barbeque": "~> 0.2.1",
```

bad things shouldn't happen when we update it using `npm update` in future. Isn't it? I could be wrong, any suggestions on doing this would be very helpful.

Also, i would like to suggest to attach a [Gemnasium](https://gemnasium.com/features) badge to the `README.md`, thus we can always be notified about the outdated packages.

And don't forget about the [![NPM version](https://badge.fury.io/js/ultimate.png)](http://badge.fury.io/js/ultimate) and [![NPM version](https://badge.fury.io/js/ultimate-seed.png)](http://badge.fury.io/js/ultimate-seed) badges that are very sexy and just waiting for your copy-paste ;)

**Comment by kerimdzhanov** [comment]
Here is the state of current `npm outdated --depth 1`:

```
Package                  Current  Wanted  Latest  Location
intern                     1.3.1   1.3.1   1.5.0  intern
karma-chrome-launcher      0.1.0   0.1.0   0.1.2  karma-chrome-launcher
karma-mocha                0.1.0   0.1.0   0.1.1  karma-mocha
ngmin                      0.4.0   0.4.0   0.4.1  ngmin
karma                     0.10.4  0.10.4  0.10.9  karma
grunt-express              0.3.6   0.3.6   1.2.1  grunt-express
protractor                0.15.0  0.15.0  0.20.1  protractor
uglify-js                  2.4.3   2.4.3  2.4.12  uglify-js
resolve                    0.5.1   0.5.1   0.6.1  matchdep > resolve
stack-trace                0.0.7   0.0.7   0.0.9  matchdep > stack-trace
globule                    0.1.0   0.1.0   0.2.0  matchdep > globule
resolve                    0.3.1   0.3.1   0.6.1  rfile > resolve
barbeque                   0.2.1   0.2.1   0.2.3  barbeque
express-winston            0.2.1   0.2.1   0.2.5  express-winston
moment                     2.4.0   2.4.0   2.5.1  moment
bindings                   1.0.0   1.0.0   1.1.1  bcrypt > bindings
lodash                     1.3.1   1.3.1   2.4.1  lodash
winston-mongodb            0.4.2   0.4.2   0.4.3  winston-mongodb
wrench                     1.5.4   1.5.4   1.5.8  wrench
coffeeify                  0.5.2   0.5.2   0.6.0  coffeeify
string                     1.5.1   1.5.1   1.8.0  string
grunt                      0.4.1   0.4.1   0.4.2  grunt
browserify                2.14.2  2.14.2  3.32.0  grunt-browserify2 > browserify
grunt-contrib-copy         0.4.1   0.4.1   0.5.0  grunt-contrib-copy
grunt-contrib-htmlmin      0.1.3   0.1.3   0.2.0  grunt-contrib-htmlmin
chai                       1.8.1   1.8.1   1.9.0  chai
grunt-contrib-imagemin     0.3.0   0.3.0   0.5.0  grunt-contrib-imagemin
grunt-contrib-connect      0.5.0   0.5.0   0.7.1  grunt-contrib-connect
grunt-contrib-jshint       0.7.2   0.7.2   0.8.0  grunt-contrib-jshint
grunt-contrib-uglify       0.2.7   0.2.7   0.4.0  grunt-contrib-uglify
grunt-contrib-less         0.8.2   0.8.2  0.10.0  grunt-contrib-less
grunt-open                 0.2.2   0.2.2   0.2.3  grunt-open
gaze                       0.4.3   0.4.3   0.5.1  grunt-contrib-watch > gaze
tiny-lr                    0.0.4   0.0.4   0.0.5  grunt-contrib-watch > tiny-lr
grunt-protractor-runner    0.2.0   0.2.0   0.2.3  grunt-protractor-runner
grunt-usemin               2.0.1   2.0.1   2.0.2  grunt-usemin
hbsfy                      1.0.0   1.0.0   1.3.2  hbsfy
express-validator          0.7.0   0.7.0   1.0.1  ultimate > express-validator
lodash                     1.3.1   1.3.1   2.4.1  ultimate > lodash
mongoose-timestamp         0.1.1   0.1.1   0.2.0  ultimate > mongoose-timestamp
mongoose                  3.6.20  3.6.20   3.8.8  ultimate > mongoose
mongoskin                  0.6.1   0.6.1  1.3.20  ultimate > mongoskin
passport                  0.1.18  0.1.18   0.2.0  ultimate > passport
passport-facebook          0.1.6   0.1.6   1.0.2  ultimate > passport-facebook
passport-twitter           0.1.5   0.1.5   1.0.2  ultimate > passport-twitter
redis                      0.8.6   0.8.6  0.10.1  ultimate > redis
unorm                      1.0.5   1.0.5   1.3.2  ultimate > unorm
connect-mongo              0.3.3   0.3.3   0.4.0  ultimate > connect-mongo
connect-redis              1.4.7   1.4.7   1.5.0  ultimate > connect-redis
express                    3.3.8   3.3.8   3.5.0  ultimate > express
request                   2.16.6  2.16.6  2.34.0  winston > request
```

**Comment by pilwon** [comment]
@kerimdzhanov So thoughtful of you to ask this question before contributing.

### Updating dependencies

We've done quite a few batch dependency updates in the past and every time we had to spend extra time and effort ensuring nothing is broken by the updates. As long as nothing is broken by the update, we'd love to do it as often as possible. It was always a manual process so the update cycle has been just not quick enough. We could probably utilize unit testing to improve the testing process. We will not be able to chase every single dependency module update though because there are simply too many that evolve all the time.

### Use of `~>` in front of dependency versions

I believe `~>` is the same thing as `~`. We used `~` for a long time, however we recently decided to fix all bower and npm versions because we saw even some popular modules are not correctly following semver. Sometimes they forget to include some files in the published package so files are missing or corrupted. We ended up fixing all version numbers because of that reason to maintain stability of `ultimate-seed`.

### `npm outdated` command

I didn't know there was `npm outdated` for this job. It would've saved us a lot of time if we knew this earlier. This tool seems to do a perfect job identifying outdated versions, but do you know of any command to bring the versions to up to date (or to wanted versions)?

### Adding more badges

If a badge could guarantee a boost of the project sexiness, then I don't see any reason not to use it. :yum: haha yeah that's a great suggestion, we'll add that in soon-

### Sending PR

Thanks again for your help! It's so great to see someone around the world sees the value in an open source project and offers help to make it better. When you send a PR, don't forget to send it to the `dev` branch.

**Comment by kerimdzhanov** [comment]
Hi @pilwon!

I suspected that there are some pitfalls on using `~>`, that's why i started this discussion.
Now i understand the lack of `Gemfile.lock` in `npm` like in `bundler` for ruby. I don't know how it may help to the project, seems this suggestion is more likely to `npm`.

Regarding to the `npm outdated` command, yeah this is very useful, and seems for now `npm update` is the only approach to update the packages inside a `node_modules` directory of your local project. Also, Gemnasium badge that i've suggested is something like `npm outdated` as a service, it will email you each time new package versions are released to `npm`, of course only those which your project is dependent on, and only if `npm outdated` will consider it as outdated for your `package.json`. Thats' why i tough that using the `~>` might be useful. Seems that unit testing coverage gaining their priority and TravisCI is waiting for us :)

Thank you too! Especially @pilwon and @yaru22! You are doing a great job! I became a big fan of `node-ultimate[-seed]`!

And sure i will send my PR to the `dev` branch, i just missed it for a first time :)

**Comment by kerimdzhanov** [comment]
Please, be sure to read this when you have a time: http://www.futurealoof.com/posts/nodemodules-in-git.html (5-7 minutes to read).

The main points are:
- Version locking doesn't makes a sense, because it locks only a top level dependencies.
- `node_modules` directory should be checked out in to the repo, but only for a deployed applications (something like an end point of source delivery), but libs and frameworks maintainers shouldn't do this.

So i'm feeling that the better approach for the seed and the main dependency (`node-ultimate`) is to have a `~` in their dependency definitions.

What do you think about it?

**Comment by andrew-luhring** [comment]
I think:
https://github.com/pilwon/ultimate-seed/issues/107
