### ISSUE TITLE
Where does the accessToken get set?

### ISSUE THREAD

**Issue by johnjelinek** [pilwon/ultimate-seed#117]
From my analysis, it seems that perhaps the accessToken is created on the first login of a new user. I have a process where an admin creates new users manually, but if leave out:

```
req.logIn(user, function (err) {
    if (err) { return _sendError(err); }
    return cb(null, user.getSafeJSON());
});
```

from the user-add process, then the access token is not generated. Should I just manually create the tokens?

**Comment by johnjelinek** [comment]
I think I can do this in the Users model in the meantime:

```
schema.pre('save', function (next) {
    var user = this;
    if (user.accessToken) {
        return next();
    } else {
        user.accessToken = ultimateUUID({ length: 30, dash: false });
        return next();
    }
});
```

**Comment by pilwon** [comment]
@johnjelinek [This is the code](https://github.com/pilwon/node-ultimate/blob/260a8d1c829bb4fac71f99b5f0245385846ce583/lib/server/express.js#L142-L173) where the `accessToken` gets updated on each Passport serialization. Are you adding this `pre` Mongoose middleware because you are getting an error? `accessToken` is something that is created on the fly so you don't need to manually assign this value.

**Comment by johnjelinek** [comment]
I'm getting an error that the accessToken already exists upon account creation. However, my flow is different, it's an invite-only type of flow. So register workflow isn't publicly accessible, rather admins manually create accounts and then the user gets notified with their login credentials. passport.serialize must not be getting called because the session never ends even though the admin is registering multiple users.

**Comment by pilwon** [comment]
@johnjelinek I understand your use case but is there a reason why you would not want to expire your user sessions?

**Comment by johnjelinek** [comment]
I want to expire the user session when the admin logs out, not upon user registration.

**Comment by pilwon** [comment]
@johnjelinek A user login session is established upon a user login, and it is terminated upon user logout (not the admin logout nor user registration). I believe I am not seeing a clear picture of the "expire the user session when the admin logs out" use case.

**Comment by johnjelinek** [comment]
The scenario is that if I reuse the existing registration function, it registers the user, and then does `req.logIn` which sets the session to the new user that just registered. I guess at that time, it does the passport serialize. I took out `req.logIn` and so prevented session resetting and passport serialization.

**Comment by pilwon** [comment]
@johnjelinek Aha, you meant not calling the serialize or logIn functions on the admin's user session. I was confused with the actual user's user session. It makes sense now.

**Comment by johnjelinek** [comment]
@pilwon yes, that's right :) Is my approach appropriate (`schema.pre('save'`)?

**Comment by pilwon** [comment]
@johnjelinek Looks like that error you mentioned occurs from the second user without an `accessToken`. (fails the uniqueness test against the first user with an empty `accessToken`) I could think of few ways to work around this error.
1. Your solution. I believe it's an easy and sound solution to this. The only downside is the `pre` middleware now needs to be called for every `save()` on the User model but the computational cost is close to nothing.
2. You only need to assign a random, unique `accessToken` value to a new user created by your admin, and this value will not be used anywhere at all because it will be reassigned upon a user login. So instead of assigning UUID, just assign something like `crypto.randomBytes(16).toString('hex')` or even `new Date().getTime()` to save unnecessary computation, and do this right at the admin's registration controller.
3. If you want to tweak and have a complete control of auth/user related things, you can always turn off the uniqueness check for [accessToken path indexing in the User schema](https://github.com/pilwon/ultimate-seed/blob/2db59e6281d0be00d0fabe56bf72d0adc0f6c9e3/server/models/User.js#L74). The uniqueness will be guaranteed later in [this code](https://github.com/pilwon/node-ultimate/blob/260a8d1c829bb4fac71f99b5f0245385846ce583/lib/server/express.js#L151-L152) so it won't be unsafe by removing this check. The benefit of this is you don't need to assign a temporary garbage value to your user documents, so you could actually use this empty value to indicate the user has never signed in.

**Comment by johnjelinek** [comment]
Cool, thanks for your suggestions!
