### ISSUE TITLE
Windows: Symbolic link to font files fails

### ISSUE THREAD

**Issue by jaulz** [pilwon/ultimate-seed#39]
It seems that the symbolic links to the font files (client/fonts) is not working on Windows machines. Is it possible to make it similar to the less/css behaviour?

So the symbolic links will be resolved and the files will be copied to the tmp folder. When the fonts folder is accessed automatically the tmp folder shall be read. Unfortunately I cannot find the place where this routing for the css files was implemented. Could you please give me a hint so I can extend it? Thanks!

**Comment by pilwon** [comment]
@jaulz Hmm symbolic link is a tricky one because that is the best way to share bower component between js/less/fonts. If you are looking for `less -> css` processing, look for `less` task in Gruntfile. <del>But I think the closest technique that avoids symbolic links is to use bower post-install hook. See how `npm-scripts.js` is called by `scripts` section in `package.json`. It automatically generates config files from sample config files. Unfortunately bower doesn't currently seem to provide this functionality like npm does. Let's find out a good solution for this.</del>

**Comment by jaulz** [comment]
@pilwon: it seems there is a misunderstanding. I actually wanted to know how you do the routing between /client/css/\* to /.tmp/css/*. You link to /css/main.css in the html file but this file does not exist and instead the main.css from the /.tmp/css folder is retrieved. My proposal to solve this problem would be to write a grunt task that  resolves all symbolic links in /client/fonts/ and copies all files to /.tmp/fonts/. Similar to the routing of the css files the fonts will then be loaded from /.tmp/fonts/.

**Comment by pilwon** [comment]
@jaulz This is what you're looking for: [ultimate's lib/server/express.js](https://github.com/pilwon/node-ultimate/blob/099fbf8de33e173ff63b8b98fa5e18514d31ff87/lib/server/express.js#L111) But since express server already treats .tmp as one of static directories, you just need to place font files in `.tmp/fonts` and copy them into `{{project.dist}}` during grunt build task. I agree with your proposal to use `.tmp/fonts` for that.
