### ISSUE TITLE
How do you become an admin via restify.model?

### ISSUE THREAD

**Issue by ghost** [pilwon/ultimate-seed#42]
I have the admin role setup on my user, but when I do a get request, it's returning the schema for user and not the \* defined for admin. Is their a different route or config piece I'm missing?

**Comment by pilwon** [comment]
@dariusriggins Just to let you know, `restify.model` functionality is still under development. Stay tuned for upcoming changes.

The first user to sign up becomes the admin user [as seen here](https://github.com/pilwon/ultimate-seed/blob/d58100463d81ad6e2030ab03bcc2e327434e1667/server/models/User.js#L116).

**Comment by cedricziel** [comment]
Hey Ho! Great work indeed :)

Sorry to ask, but how can i resolve this in the current state of ultimate?
I need the differentiation between the roles and would like to know if there are any news on that topic?

Cheers,
Cedric

**Comment by pilwon** [comment]
@cedricziel For differentiating result based on user roles all you need to do is checking the `req.user.roles` string array. Using underscore/lodash, `_.has(req.user.roles, 'somerole')` check would do the job.

Restify module that is currently included in the seed only works partially. I'd say it's at the proof of concept stage.

**Comment by cedricziel** [comment]
Thank you for the explanation @pilwon . To be honest: The restify module is becoming one of my main interests (as you tied the other components together almost perfectly ;) ). Do you have a rough schedule or pin point me where I should try to improve it?

Afaik the roles are doing their job quite good-except the matching has a priority problem.

**Comment by pilwon** [comment]
@cedricziel Thanks for looking at it that way. Almost feel guilty for not completing the work I started off on that. The project collaborator @yaru22 and I are both blocked with other things right now therefore we have not been able to tackle on open issues lately. It may take few more weeks for either of us to come back to this project.

If you are interested in contributing to this project especially the restify module, we'll be very happy to merge your PR and appreciate your help. You probably already have a good idea about how we envision restify config part in `schema.restify` of `server/model/*.js` and `server/routes.js`. We'd like to keep that API description format for now but we may switch to [RAML](http://raml.org/) later on. ([related issue](https://github.com/pilwon/ultimate-seed/issues/59)) In terms of feature set, we'd like to benchmark features of [baucis](https://github.com/wprl/baucis) yet we integrate tightly with our own roles system. In order to go from the proof-of-concept to perfect solution, we will need to clean up [all `_expand` functions in the restify module](https://github.com/pilwon/node-ultimate/blob/master/lib/server/route/restify.js) (possibly rewrite the entire file) because it's too messy right now. Please let us know if you have any specific question on improving restify.

**Comment by cedricziel** [comment]
I'm coming from a PHP context and was fighting with Node (for good!) for the last 2 weeks. Just to make sure you see my background.

In that time I had intermezzos with both baucis and the original restify server. The first impressed me like nothing else. The original restify server was quite unusable for me, as I need it to be a part of my express app.

I will dig deeper into the places you pointed at and let you know if I can do anything.
