### ISSUE TITLE
Using rhtml with Angular's $templateCache.

### ISSUE THREAD

**Issue by yaru22** [pilwon/ultimate-seed#47]
Right now, we're using rhtml to minify template and inlining it to views. i.e.

```
ngModule.config(function ($stateProvider) {
  $stateProvider
    .state('app.admin', {
      url: '/admin',
      views: {
        '@': {
          controller: 'MainCtrl',
          template: rhtml('./templates/main.html')
        }
      }
    });
});
```

However, this could increase the code size if more than one controller shares the same template. I think the better approach would be, for example,

```
angular.module('app.admin.template', []).run(function($templateCache) {
  $templateCache.put('adminMain.html', rhtml('./templates/main.html'));
});
```

and then

```
'@': {
  controller: 'MainCtrl',
  templateUrl: 'adminMain.html'
}
```

This way, even if there are multiple controllers that want to use the same template, we are going to include it in our code base only once.

**Comment by pilwon** [comment]
It is unnecessary to use `$templateCache` because template code sharing can be easily achieved by any of the following techniques:
- Move `rhtml('./templates/*.html')` to the top of `{{module}}/index.js` then assign the loaded template to multiple states.
- Load and cache all templates that need to be shared to a separate JS file then require this file from module state definition block. Let Browserify resolve `exports.*`.
- Use abstract ui-router state.
- Use `$templateCache` or even create a simple reqres-type angular service.
