### ISSUE TITLE
Facebook registration without living the single page app

### ISSUE THREAD

**Issue by remicastaing** [pilwon/ultimate-seed#55]
Neither the [MEAN-stack by Linovate](https://github.com/linnovate/mean) nor the demo from @madhums do it: could it be possible to perform a FB/Google/Tw/etc. registration without living the single page app? Perhaps through a modal view.
The purpose of this question is to run the app inside a phonegap container.

**Comment by pilwon** [comment]
@remicastaing Not sure if I understood your question correctly.

If what you like to have is social integrations without need of Angular single-page app, it's already implemented that way. Just redirect user to one of these end points:
- http://ultimate-seed.herokuapp.com/auth/facebook
- http://ultimate-seed.herokuapp.com/auth/google
- http://ultimate-seed.herokuapp.com/auth/twitter

**Comment by remicastaing** [comment]
I do want an Angular SPA and social integration. But if I click 
http://ultimate-seed.herokuapp.com/auth/facebook
I'm living the SPA to the FB registration page and after the registration is completed, I'm redirected to 
http://ultimate-seed.herokuapp.com//auth/facebook/success

I'm wondering if it is possible to avoid this two redirections and having the registration proceeded inside a modal view or inside another brother windows/tab.

This would allow to write a pure static angular app served by an nginx server, and relying on REST services served by node.

**Comment by pilwon** [comment]
@remicastaing I see what you want. You'd need to look into [Facebook JavaScript SDK](https://developers.facebook.com/docs/facebook-login/getting-started-web/) to achieve that. I've done it on my other project and it's fairly straight forward to implement.

You'll need to receive the auth cookie returned from FB server to user's browser when user makes a request to the ultimate server. Then you need to do custom token handling (save, create/update user, then authenticate user session).

The reason why `ultimate-seed` (and probably others too) doesn't support this is simply because it is not really necessary to do it this way. It requires the Angular app to load and inject Facebook's JavaScript SDK and do some custom auth handling that is not consistent with other Passport-compatible auth strategies. Sure, there's UX improvement but it's not worth the effort in most cases.

**Comment by remicastaing** [comment]
Thank you for this explanation, @pilwon.

My main concern was to be able to put the app without change in a  Cordova/PhoneGap container. But, it's probably not a so good idea: one would be better of by using some Cordova Facebook plugin and the native Facebook app to perform Single Sign On for the user.

**Comment by pilwon** [comment]
@remicastaing Oh yes definitely use the already available Facebook auth plugin for Cordova app. I forgot you wanted it for your mobile app. Using something based on Facebook's mobile SDK will provide the best user experience and security.
