### ISSUE TITLE
How to use Ultimate-seed?

### ISSUE THREAD

**Issue by steve21124** [pilwon/ultimate-seed#65]
lets say, I would like to add "posts" menu that retrieve posts.json from the server and render it to the page
## http://localhost:3000/posts

From your Ultimate-seed layout.
Choice 1  -- create a new posts directory
- add "posts" to layout/templates/_nav.html
- in client/js/app.js -- add "app.posts" to ngModule
- in client/posts/index.js -- create app.posts
- in client/posts/templates/posts.html

Choice 2 --- or create it part of "express"
like express.posts, express.users, etc

Which one is a good choice?
thanks

**Comment by pilwon** [comment]
@steve21124 

We haven't yet documented this but the seed is quite flexible enough that you have many options when adding a new page. The seed includes simple example code for each option: angular, express, and static, and template-less. You may also create your own layout similar to `static`.

It's pretty much case-by-case when deciding the best implementation option for a new page.

If it is something good to be part of Angular SPA, then you definitely want to go with your Choice 1. You don't need to add anything to server routes since it has catch-all route in place. You can either put your posts route/controller/view in a new module or in an existing module such as `main`. How you slice your pages and features into angular modules is completely up to you. Just remember to inject and load any new module in `client/js/index.js` and `client/js/app.js` (refer to https://github.com/pilwon/ultimate-seed/pull/58) and follow the convention in other module. Otherwise it may not work for you.

If you want your new page be stand-alone or you don't want it to be part of the main angular app flow, you can place it on the server-side using any other options mentioned above. You need to touch `server/routes.js` in this case. You can load a page without data then use jQuery (or any alternative) to send ajax request for data loading. You can also render it directly from express by passing the JS object to a view in your controller. In this case you'll be using handlebars template.
