### ISSUE TITLE
transactional emails

### ISSUE THREAD

**Issue by bluepeter** [pilwon/ultimate-seed#68]
Would be nice to get some transactional emails (possibly even via Sendgrid API) for various activities: completing reports, etc.

Okay, may be expanding this sucker out a bit beyond a seed. But, still, there usually always needed!

**Comment by pilwon** [comment]
@bluepeter Great idea. Indeed we started email support by first putting it in our config files. We'd like to integrate it using [NodeMailer](https://github.com/andris9/Nodemailer). (comes with SendGrid support as well) Closing this issue  since it's related to https://github.com/pilwon/ultimate-seed/issues/28
