### ISSUE TITLE
How to authenticate a request via token?

### ISSUE THREAD

**Issue by cedricziel** [pilwon/ultimate-seed#72]
Hi,

I just discovered, there's an accessToken feature-including serialization and deserialisation-how would i issue requests that get actually authenticated by the accesstoken?

Thanks in advance,
Cedric

**Comment by pilwon** [comment]
@cedricziel Have a look at [this code](https://github.com/pilwon/node-ultimate/blob/b7a53ca0a7dae303374ba49cd6cbbf0a6879d62d/lib/server/express.js#L142).

**Comment by cedricziel** [comment]
Thank you for the quick response!

A look at that passage was actually the reason for me to ask here ;)

How would a request that gets successfully authenticated look like?

`GET /api/:resource?token=myToken` ?

Sorry for nagging you about that..

**Comment by pilwon** [comment]
@cedricziel It's done using session cookie. Please refer to `Sessions` section of [Passport Documentation](http://passportjs.org/guide/configure/)

**Comment by cedricziel** [comment]
Aha! :)

Sorry, seems i got the whole thing wrong.. I thought this was a bearer token I could use inside API requests fx.

**Comment by pilwon** [comment]
@cedricziel Yeah I feel you. It took me a while to gain a thorough understanding of passport mechanism when I set this up a while ago.

**Comment by cedricziel** [comment]
Would you mind having a fifth strategy implemented with passport-bearer? I would try my very best upon this ;)

I'd really like the idea to be able to authenticate via headers as they would be encrypted as well.

**Comment by pilwon** [comment]
@cedricziel Is this what you're referring to? https://github.com/jaredhanson/passport-http-bearer

**Comment by cedricziel** [comment]
Yessir!

**Comment by pilwon** [comment]
@cedricziel Looks like it's also parsing `access_token` body & query params besides `Authorization` header field. I don't think most apps need a separate `access_token` field support unless it is built to function as a pure API server. Moreover, `ultimate-seed` is too fat for a pure API server case because it contains too many unused parts. It'll be much cleaner and wiser to build an express app from scratch. So I'd like to stick to the current think it's better to stick with the session cookies. I don't really see a need for passing the actual token back and forth in every call.

**Comment by cedricziel** [comment]
I hear you.

In fact I started with ultimate bc you tied it all together so nicely.
Hm.

This makes me think about if ultimate is the right tool for my use-case.

I thought I'd use ultimate because you showed it very good how one can have dynamic, static and api-resources sitting side by side.

**Comment by pilwon** [comment]
@cedricziel In most scenarios `ultimate-seed` can take you very far. It's not a simplified web framework that abstracts away some of the powerful yet not frequently used features. Instead our approach simply wires and configures common things for you so you have a complete access to all the pieces for full customization. (ex: Express, Mongoose, Winston, Angular ,etc.) It's obviously opinionated in terms of choices made in terms of what building blocks are used. However if you agree with most of those decisions, you will be very happy with the seed and it will scale beautifully because of its modular, complex case minded design. Also, I bet you will end up with something pretty similar even when you build and wire everything by yourself.

Having said that, like I said above, there are certain scenarios where you might want to take it from ground zero. I believe Pure API server is one of them. You don't need anything in `client/` because there is no client-side. On the server-side, you can remove a lot of middlewares and the entire views directory can go away as well. Then what remains is just a bunch of straightforward modules simply wiring models and controllers backed by raw Express (or even Connect server). If this is what you'll end up with, there's no point of starting with a seed that is way too fat for your needs. `ultimate-seed`, in this case, could still be a big time-saver for you because almost all answers you would normally google when building your server are found here.
