### ISSUE TITLE
AngularJS - Load directive HTML template via templateURL - i get a "page reload loop"

### ISSUE THREAD

**Issue by Kyii** [pilwon/ultimate-seed#77]
AngularJS related: if i try to load a directive HTML template via templateURL i get a page reload loop. inline template works fine.

i guess my "issue" is connected to the "module.exports" concept of node which i don't understand enough now. 

can someone point me in the right direction or give some advice?
thanks.

**Comment by pilwon** [comment]
@Kyii In order to use templateUrl you need to make sure template files are actually served by the web server. The easiest way is to place all lazy loaded template files in the `static` directory by mirroring directory path of angular module templates (or use symlink). Otherwise you'll need to attach static express middlewares for `client/js/*/templates`.

**Comment by Kyii** [comment]
@pilwon thanks! very much appreciated.

**Comment by maximkott** [comment]
Still, it would be nice if there would be an exception in the console instead of page freeze (loading loop). You can't even close the tab - have to kill chrome.

Tracking down such an issue is quite hard because you would think of a script to cause this.

**Comment by dudewad** [comment]
I'm experiencing this, even now. This seems like a major issue that should be caught internally by the templateURL handler. What if server resources change? Is it really necessary for an entire page to come down because dev A didn't know about dev B's setup?
