### ISSUE TITLE
Blank page on startup (FSEventStreamStart: register_with_server)

### ISSUE THREAD

**Issue by theganyo** [pilwon/ultimate-seed#88]
Using either Yeoman or Git Clone to install (I tried both), I get nothing but a blank screen in the browser when I run grunt. This is what I did:

```
$ git clone https://github.com/pilwon/ultimate-seed.git ultimate-seed
$ cd ultimate-seed/
$ npm install && bower install
$ grunt build
$ grunt
```

This fails with the error:

> Fatal error: Server ["/ultimate-seed/server"] -  Error: Could not load the bindings file.

So I did a rebuild...

```
$ npm rebuild
$ grunt
```

At this point I get a blank screen in the browser. This is at the end of the console:

> Waiting...GET / 200 50ms
> GET /js/main.js?1390932511040 200 10ms - 0b
> GET /js/vendor/modernizr.js?1390932511040 200 16ms
> GET /css/main.css?1390932511040 200 28ms
> GET /js/node_modules/bower_components/animate.css/animate.css 200 4ms
> 2014-01-28 10:09 grunt[79979](CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

(Actually, many of those ERROR lines... but they aren't emitted again after the first request - ie. if I do a refresh from the browser.)

Side note: I thought it odd that /js/main.js has zero bytes?

Any thoughts on resolving this?

Thanks!
Scott

**Comment by hbzhang** [comment]
I exactly get the same thing as you. This definitely should be fixed. U - S is a great project, which should deliver more amazing stuff to people right after fresh install.

**Comment by theganyo** [comment]
Sounds good! :)  

In the mean time, I'm new to most of the packages included in the stack and I don't know where to start to get this working (or how to build on it for that matter). I was hoping to jumpstart a new project with a nice, complete stack like this... but is this maybe not the best base to start with?

**Comment by yaru22** [comment]
@scottganyo, what version of node (node --version) and what OS are you using? I just did a fresh install on my Ubuntu 13.04 64bit with node v0.10.25 and except for a bower package hiccup (angular-ui-router), which @pilwon is fixing right now, I didn't have any problem that you mentioned. Maybe knowing what node version and OS you are using might help us identify the problem?

**Comment by theganyo** [comment]
Good point! Node v.0.10.25 on OS X 10.9.1. (Both are the latest stable versions.)

**Comment by pilwon** [comment]
@scottganyo @hbzhang Thanks for reporting guys.

> ... bower package hiccup (angular-ui-router), which @pilwon is fixing right now ...

The fix was committed 6a625a9e5c8a0f926cd08d01d476a2f3bb58fa0f. Please pull the latest version from the master branch and run `bower install && npm install` and `grunt` again. I have a feeling that `FSEventStreamStart` is an isolated issue that's just a warning message, therefore this fix could possibly fix the empty page issue you experienced. You would've see a blank page because JS file cannot be built during `browserify` grunt task.

**Comment by theganyo** [comment]
Fantastic. Thanks!

**Comment by pilwon** [comment]
@scottganyo Does it work? Do you still see the `FSEventStreamStart` error message? Please try and share the result with us. (cc: @hbzhang)

**Comment by pilwon** [comment]
> In the mean time, I'm new to most of the packages included in the stack and I don't know where to start to get this working (or how to build on it for that matter). I was hoping to jumpstart a new project with a nice, complete stack like this... but is this maybe not the best base to start with?

@scottganyo `ultimate-seed` can meet all kinds of usage scenarios and the main benefit is that it is a AngularJS + Express based seed rather than a whole new framework. Everything you learn from this project can be directly applied to and shared with other projects. Learning how to build an app using `ultimate-seed` means learning Express, AngularJS, Mongoose, and others that you would normally use to build a modern web application anyways. This seed only wires things together for you and has basic parts (auth, session, config, etc.) already built for you. You don't need to learn any new framework that you may use today but never afterwards. The main reason documentation is kept simple is because once you have some understanding and experience with the (well-documented) dependencies, you will quickly realize things are organized in a straight-forward way. But we do believe improvement on it would expedite learning process. I'd say `ultimate-seed` is the ultimate learning resource for building a modern Node.js-based web application if that's what you're looking for.

**Comment by theganyo** [comment]
@pilwon @hbzhang Yes, the update worked. Thanks! But, yes, unfortunately I still do get the FSEventStreamStart error.

Thanks for the explanation of U-S. I'm planning to give it a go and see where it takes me!

**Comment by hbzhang** [comment]
Great. Thanks for the quick fix!
