### ISSUE TITLE
De-couple Ultimate Seed from Ultimate Seed Library.

### ISSUE THREAD

**Issue by bluepeter** [pilwon/ultimate-seed#99]
Can I recommend that a set-up option might be to fully de-couple Ultimate Seed from the [Ultimate Seed Library](https://github.com/pilwon/node-ultimate)?

The reason for this is because that library contains a lot of custom code, particularly the Restify stuff. As you noted in an issue in that repo about that functionality, it's quite limited (e.g., doesn't accept params) and designed for the rather limited API needs in Ultimate Seed.

It'd be nice to be able to more easily de-tangle that from Ultimate. Love what you guys have done, but Restify is an awful lot of custom code without much documentation and with a fairly narrow use case (Ultimate Seed).

**Comment by pilwon** [comment]
@bluepeter Thanks for opening request.

We acknowledge this problem you pointed out. A complete de-coupling might be a problem though because some common boilerplate code are better be shared among multiple projects for other reasons. However, a significant cleanup and structural re-design are planned for the `koa` branch that is a new branch we started to target the new `node --harmony` environment.

For your information, right now, you can already very easily choose not to use Restify code. Simply do not call it from `server/routes.js`. This seed gives you the raw power after all, so if you understand Express routes and Mongoose models, you can can always create one that works best for you.

**Comment by bluepeter** [comment]
Thanks, good call.

I now understand a bit more about native routes in Express. However, since I was using Ultimate to learn, I didn't initially: and I figured that Restify was either a separate third-party module, or just "the way to do things."

It took a bit of digging around to find that it was your custom code. I'd perhaps highlight that in comments. (It doesn't help that the name, Restify, is shared by another Node module... which I was foolishly reading up on until I dug into the dependency library.)

Btw, and take this as a question from a novice, are you planning to swap out Express for Koa? It kinda looks like it from a perusal of that branch?

**Comment by pilwon** [comment]
@bluepeter We are destined to move to `koa` because that's the future of node.js programming but we will not completely swap out Express until Koa gets stable enough. That means Express will likely to stay for a while.
